name: Build CSV

concurrency:
  group: build-csv
  cancel-in-progress: false

on:
  push:
    paths:
      - 'logs/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate CSV
        run: |
          python scripts/build_csv.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add reports/line_message_log.csv

          if ! git diff --cached --quiet; then
            git commit -m "Update line_message_log.csv"
          fi

      - name: Pull latest
        run: |
          git pull --rebase origin main

      - name: Push
        run: |
          git push origin main
